version: "3.8"

services:
  web:
    build: .
    container_name: place-repository-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.aws:/home/myuser/.aws
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres:15
    container_name: place-repository-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=place_repository
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
