"""Make unique the country name

Revision ID: 0798ca3cbf78
Revises: 7a9588dbc0b7
Create Date: 2025-08-25 14:01:13.442377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0798ca3cbf78'
down_revision: Union[str, Sequence[str], None] = '7a9588dbc0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_country_country_name'), 'country', ['country_name'], unique=True)
    op.create_unique_constraint(None, 'country', ['country_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_index(op.f('ix_country_country_name'), table_name='country')
    # ### end Alembic commands ###
