"""Add Continent Model

Revision ID: 7a9588dbc0b7
Revises: 5bfccc5d5401
Create Date: 2025-08-25 13:54:03.836582

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9588dbc0b7'
down_revision: Union[str, Sequence[str], None] = '5bfccc5d5401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continent',
    sa.Column('continent_id', sa.Integer(), nullable=False),
    sa.Column('continent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('continent_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('continent_id')
    )
    op.add_column('country', sa.Column('continent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'country', 'continent', ['continent_id'], ['continent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='foreignkey')
    op.drop_column('country', 'continent_id')
    op.drop_table('continent')
    # ### end Alembic commands ###
